### ISSUE TITLE
TypeError: Cannot read property 'newLine' of undefined

### ISSUE THREAD

**Issue by cyroxx** [sea-watch/SAR-Client#209]
## Environment

- App version: 0.0.1-beta.17 (dc22d67e0b13c392d1508efd85e15aaf8bf6634f)
- Operating System: Xubuntu 16.04

## Issue

I cannot build the app. Please see the console output below.

```
cyroxx@melua:~/Entwicklung/SAR-Client$ npm run electron

> sar-client@0.0.1-beta.17 electron /home/cyroxx/Entwicklung/SAR-Client
> run-s ng:build electron:start


> sar-client@0.0.1-beta.17 preng:build /home/cyroxx/Entwicklung/SAR-Client
> run-s fmt generate:all


> sar-client@0.0.1-beta.17 fmt /home/cyroxx/Entwicklung/SAR-Client
> tsfmt -r --baseDir src


> sar-client@0.0.1-beta.17 generate:all /home/cyroxx/Entwicklung/SAR-Client
> run-s generate:version


> sar-client@0.0.1-beta.17 generate:version /home/cyroxx/Entwicklung/SAR-Client
> node script/generate-version.js


> sar-client@0.0.1-beta.17 ng:build /home/cyroxx/Entwicklung/SAR-Client
> ng build

Hash: c67a5e1337f37c98610e                                                         
Time: 2346ms
chunk    {0} styles.bundle.js, styles.bundle.js.map (styles) 10 kB {2} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 483 bytes [initial] [rendered]
chunk    {2} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (/home/cyroxx/Entwicklung/SAR-Client/node_modules/typescript/lib/typescript.js:9514:20)
    at Object.createCompilerHost (/home/cyroxx/Entwicklung/SAR-Client/node_modules/typescript/lib/typescript.js:63770:26)
    at Object.ngcLoader (/home/cyroxx/Entwicklung/SAR-Client/node_modules/@ngtools/webpack/src/loader.js:329:31)
 @ multi ./src/main.ts

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "ng:build"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sar-client@0.0.1-beta.17 ng:build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sar-client@0.0.1-beta.17 ng:build script 'ng build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sar-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sar-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sar-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cyroxx/Entwicklung/SAR-Client/npm-debug.log
ERROR: "ng:build" exited with 1.

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "electron"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sar-client@0.0.1-beta.17 electron: `run-s ng:build electron:start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sar-client@0.0.1-beta.17 electron script 'run-s ng:build electron:start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sar-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     run-s ng:build electron:start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sar-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sar-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cyroxx/Entwicklung/SAR-Client/npm-debug.log
```

## Steps to Reproduce

1. Follow the installation steps in README.md
2. Run `npm run electron`

## Expected
`npm run electron` succeeds.

**Comment by cyroxx** [comment]
`ng version` gives:

```
angular-cli: 1.0.0-beta.25.5
node: 6.11.1
os: linux x64
@angular/cli: 1.2.1
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/compiler-cli: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
```

**Comment by cyroxx** [comment]
It seems that the problem was the `angular-cli` package that was still installed.

After uninstalling that, `npm list --depth=0` listed webpack and file-loader as missing peer dependencies, so I installed them manually. If you have any tips about what is the correct way to usually deal with these missing peer deps, please let me know.

So finally I got the app to show up. That said, README.md states 
```
This project was generated with angular-cli version 1.0.0-beta.25.5.
```
Is this still true? Or should this comment be removed since the dependency is managed through `package.json`?

**Comment by niczem** [comment]
yep you are right, I'll remove it. Thanks!
